Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using practise.BookStoreApp.Models;
using practise.BookStoreApp.Repository;

namespace practise.BookStoreApp.Controllers
{
    public class BookController : Controller
    {
        private readonly BookRepository _bookRepository = null;
        private readonly LanguageRepository _languageRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment = null;

        public BookController(BookRepository bookRepository, LanguageRepository languageRepository,
            IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<ViewResult> GetAllBooks()
        {
            var data= await _bookRepository.GetAllBooks();
            return View(data);
        }

        public async Task<BookModel> GetBook(int id)
        {
            var data = await _bookRepository.GetBookById(id);
            return data;
        }

        public List<BookModel> SearchBooks(string bookName , string authorName)
        {
            return _bookRepository.SearchBook(bookName, authorName);
            
        }

        [Route("book-details/{id}", Name = "bookDetailsRoute")]
        public async Task<ViewResult> GetBookDetail(int id)
        {
            var data = await _bookRepository.GetBookById(id);
            return View(data);
        }

        public async Task<ViewResult> AddNewBook(bool isSuccess = false, int bookId =0)
        {
            var model = new BookModel()
            {
                //Language = "2"
            };
            //var group1 = new SelectListGroup() { Name = "Group 1" };
            //var group2 = new SelectListGroup() { Name = "Group 2" };
            //var group3 = new SelectListGroup() { Name = "Group 3" };

            // ViewBag.Language = new SelectList(GetLanguage(), "Id", "Text");
            //ViewBag.Language = GetLanguage().Select(x => new SelectListItem()
            //{
            //    Text = x.Text,
            //    Value= x.Id.ToString()

            //}).ToList();

            //ViewBag.Language = new List<SelectListItem>()
            //{
            // new SelectListItem(){Text="Hindi", Value="1", Group = group1},
            // new SelectListItem(){Text="English", Value="2",Group = group1},
            // new SelectListItem(){Text="Dutch", Value="3", Group = group2},
            // new SelectListItem(){Text="Kannada", Value="4",Group = group2},
            // new SelectListItem(){Text="Konkani", Value="5", Group = group3},
            // new SelectListItem(){Text="Tulu", Value="6", Group = group3},

            //};
            ViewBag.Language =new SelectList( await _languageRepository.GetLanguages(),"Id","Text");
            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
           
            if (ModelState.IsValid)
            {
                if (bookModel.CoverPhoto != null)
                {
                    string folder = "books/cover/";
                    bookModel.CoverImageURL= await UploadImage(folder, bookModel.CoverPhoto);
                }
                if (bookModel.GalleryFiles != null)
                {
                    string folder = "books/gallery/";

                    bookModel.Gallery = new List<GalleryModel>();

                    foreach(var file in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImage(folder, file)
                        };
                        bookModel.Gallery.Add(gallery);
                    }
                }

                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBook), new { isSuccess = true, bookId = id });
                }
            }
            //var group1 = new SelectListGroup() { Name = "Group 1" };
            //var group2 = new SelectListGroup() { Name = "Group 2" };
            //var group3 = new SelectListGroup() { Name = "Group 3" };
            //ViewBag.IsSuccess = false;
            //ViewBag.BookId = 0;
            // ViewBag.Language = new SelectList(GetLanguage(), "Id", "Text");
            //ViewBag.Language = new List<SelectListItem>()
            //{
            // new SelectListItem(){Text="Hindi", Value="1", Group = group1},
            // new SelectListItem(){Text="English", Value="2",Group = group1},
            // new SelectListItem(){Text="Dutch", Value="3", Group = group2},
            // new SelectListItem(){Text="Kannada", Value="4",Group = group2},
            // new SelectListItem(){Text="Konkani", Value="5", Group = group3},
            // new SelectListItem(){Text="Tulu", Value="6", Group = group3},
            //};
            ViewBag.Language = new SelectList(await _languageRepository.GetLanguages(), "Id", "Text");
            ModelState.AddModelError("", "This is custom error message");
            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverfolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverfolder, FileMode.Create));

            return "/" + folderPath;
        }

        //hardcoded select values
        //private List<LanguageModel> GetLanguage()
        //{
        //    return new List<LanguageModel>()
        //    {
        //         new LanguageModel(){Id=1, Text="Hindi"},
        //         new LanguageModel(){Id=2, Text="Kannada"},
        //         new LanguageModel(){Id=3, Text="English"}
        //    };
        //}
    }
}

Views/Book/AddNewBook.cshtml
@using practise.BookStoreApp.Enum
@model BookModel

@{
    ViewData["Title"] = "Add new books|";
}
    <div class="container">
        <h3 class="display-3"> Add New Books</h3>
        <hr />
        @if (ViewBag.IsSuccess == true)
        {
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> You should check in on some of those fields
                <a asp-controller="Book" asp-action="GetBookDetail" asp-route-id="@ViewBag.BookId">here</a>.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @*below code is for loader*@
        @*<div class="d-flex justify-content-center"  style="display:none">
            <div class="spinner-border" role="status" id="myLoader">
                <span class="sr-only">Loading...</span>
            </div>
        </div>*@

        @*below form tag for jquery.unobstrusive.ajax.*@

        @*<form method="post" data-ajax-loading="#myLoader" data-ajax="true" data-ajax-failure="myFailure" data-ajax-complete="myComplete" data-ajax-success="mySuccess" asp-action="AddNewBook" asp-controller="Book">*@
    <form method="post" enctype="multipart/form-data" asp-action="AddNewBook" asp-controller="Book">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            @*bellow code using viewbag
             <label asp-for="MultiLanguange"></label>
             <select asp-for="MultiLanguange" class="form-control" asp-items="ViewBag.Language" multiple>
             <option value="">Please select a langauage</option>
            </select>
             <span asp-validation-for="MultiLanguange" class="text-danger"></span>*@
            @*<label asp-for="LanguageId"></label>
            <select asp-for="LanguageId" class="form-control" asp-items="Html.GetEnumSelectList<LanguageEnum>()">
                <option value="">Please select a langauage</option>
            </select>
            <span asp-validation-for="LanguageId" class="text-danger"></span>*@
            <label asp-for="LanguageId"></label>
            <select asp-for="LanguageId" class="form-control" asp-items="ViewBag.Language">
                <option value="">Please select a langauage</option>
            </select>
            <span asp-validation-for="LanguageId" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label class="control-label" asp-for="MyField"></label>
            <input asp-for="MyField" class="form-control" />
            <span asp-validation-for="MyField" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Author" class="control-label"></label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <textarea type="text" asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Pages" class="control-label"></label>
            <input type="number" asp-for="Pages" class="form-control" />
            <span asp-validation-for="Pages" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CoverPhoto" class="control-label"></label>
            <div class="custom-file">
                <input asp-for="CoverPhoto" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <span asp-validation-for="CoverPhoto" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="GalleryFiles" class="control-label"></label>
            <div class="custom-file">
                <input asp-for="GalleryFiles" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <span asp-validation-for="GalleryFiles" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Add Book" class="btn btn-primary" />
        </div>
    </form>
    </div>

@section scripts { 
<script>
    function myComplete() {
        alert("I am from complete")
    }
    function mySuccess() {
        alert("I am from success")
    }
    function myFailure() {
        alert("I am from failure")
    }
</script>
}

Views/Book/GetAllBooks.cshtml
@model IEnumerable<practise.BookStoreApp.Models.BookModel>



    <div class="container">

        <h3 class="display-4">List of all books</h3>
        <div class="row">
            @foreach (var book in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        @*<svg class="bd-placeholder-image card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" alt="Card image cap"></svg>*@
                        <img src="@book.CoverImageURL" class="img-thumbnail"/>
                        <div class="card-body">
                            <h3 class="card-title">@book.Title</h3> <p>@book.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="book" asp-action="GetBookDetail"  asp-route-id="@book.Id" asp-fragment="similarBooks" class="btn btn-sm btn-outline-secondary">View details</a>
                                </div>
                                <small class="text-muted">@book.Author</small>
                            </div>
                        </div>
                    </div>
                </div>

            }

        </div>
    </div>
   

Views/Book/GetBookDetail.cshtml
@model BookModel
@{ 
    ViewData["Title"] = Model.Title;
}
<div class="container">
    <h3 class="display-4">Book details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count; i++)
                    {
                        <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0?"active":"")"></li>

                    }
                    @*<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>*@
                </ol>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count; i++)
                    {
                        <div class="@(i==0?"carousel-item active":"carousel-item")">
                            <img class="d-block w-50" src="@Model.Gallery[i].URL" alt="@Model.Gallery[i].Name">
                        </div>
                    }


                    @*<div class="carousel-item active">
                        <img class="d-block w-50" src="~/images/book/itc.jpg?auto=yes&bg=666&fg=444&text=First slide" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-50" src="~/images/book/wof.jpg?auto=yes&bg=666&fg=444&text=Second slide" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-50" src="~/images/book/ATME.jpg?auto=yes&bg=555&fg=333&text=Third slide" alt="Third slide">
                    </div>*@
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h1>@Model.Title</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-primary">
                        <span class="label label-primary">By:</span>
                        <span class="monospace">@Model.Author</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="description">@Model.Description</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                       <button class="btn btn-outline-primary">Read Now</button>
                    </div>
                </div>
                <hr />
                <ul class="list-group">
                    <li class="list-group-item"><span class="font-weight-bold">Category-</span>@Model.Category</li>
                    <li class="list-group-item"><span class="font-weight-bold">Total Pages-</span>@Model.Pages</li>
                    <li class="list-group-item"><span class="font-weight-bold">Language-</span>@Model.Language</li>
                </ul>
            </div>
        </div>
        <hr />
        <div class="py-5 bg-light" id="similarBooks">
            <h3 class="h3">Similar Books</h3>
            <div class="row">
                @for (int i = 0; i < 5; i++)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-image card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" alt="Card image cap"></svg>
                            <div class="card-body">
                                <h3 class="card-title">book.Title</h3> <p>bookDescription</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="/book/getbookdetail/book.Id" class="btn btn-sm btn-outline-secondary">View details</a>
                                    </div>
                                    <small class="text-muted">bookAuthor</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>
</div>